import {NextResponse} from "next/server";

export async function GET(req:Request){
 const installUrl=process.env.SHOPIFY_INSTALL_URL?.trim();
 if(!installUrl){
  return NextResponse.json({ok:false,error:"Shopify installation is not configured yet. Set SHOPIFY_INSTALL_URL to the install URL generated by Shopify for this app."},{status:503});
 }
 try{
  const target=new URL(installUrl);
  if(target.protocol!=="https:"||!target.hostname.endsWith("shopify.com"))throw new Error("invalid");
  return NextResponse.redirect(target);
 }catch{
  return NextResponse.json({ok:false,error:"SHOPIFY_INSTALL_URL is invalid."},{status:503});
 }
}
