"use client";
import {FormEvent,useState} from "react";
import {ArrowRight,ShieldCheck} from "lucide-react";

export default function AuthPage(){const [mode,setMode]=useState<"signup"|"login">("signup");const [name,setName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch(`/api/auth/${mode}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,email,password})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"Authentication failed");window.location.href="/";}catch(e){setError(e instanceof Error?e.message:"Authentication failed");}finally{setBusy(false)}}
 return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#0b0d10",color:"#f5f7fa",fontFamily:"Inter,system-ui,sans-serif",padding:24}}><div style={{width:"100%",maxWidth:460,border:"1px solid #252a31",borderRadius:20,padding:32,background:"#111419",boxShadow:"0 20px 80px rgba(0,0,0,.35)"}}><div style={{fontSize:14,letterSpacing:.5,marginBottom:28}}>◆ <b>TenTran AI</b></div><div style={{marginBottom:24}}><h1 style={{fontSize:30,margin:"0 0 8px"}}>{mode==="signup"?"Create your account":"Welcome back"}</h1><p style={{color:"#9ca3af",margin:0}}>One account owns your workspace and keeps your connector connections with you.</p></div><form onSubmit={submit} style={{display:"grid",gap:14}}>{mode==="signup"&&<label style={{display:"grid",gap:7,fontSize:13}}>Name<input value={name} onChange={e=>setName(e.target.value)} required placeholder="Your name" style={input}/></label>}<label style={{display:"grid",gap:7,fontSize:13}}>Email<input value={email} onChange={e=>setEmail(e.target.value)} required type="email" autoComplete="email" placeholder="you@company.com" style={input}/></label><label style={{display:"grid",gap:7,fontSize:13}}>Password<input value={password} onChange={e=>setPassword(e.target.value)} required minLength={8} type="password" autoComplete={mode==="signup"?"new-password":"current-password"} placeholder="At least 8 characters" style={input}/></label>{error&&<div style={{padding:12,borderRadius:10,background:"#2a1517",color:"#ffb4b4",fontSize:13}}>{error}</div>}<button disabled={busy} style={{...button,opacity:busy?.65:1}}>{busy?"Please wait…":mode==="signup"?"Create account":"Sign in"}<ArrowRight size={16}/></button></form><div style={{display:"flex",alignItems:"center",gap:8,color:"#8b93a1",fontSize:12,marginTop:18}}><ShieldCheck size={14}/> Your connector credentials stay server-side and encrypted.</div><div style={{display:"flex",alignItems:"center",gap:10,marginTop:18}}><div style={{height:1,background:"#252a31",flex:1}}/><span style={{color:"#697180",fontSize:12}}>or</span><div style={{height:1,background:"#252a31",flex:1}}/></div><a href="/api/auth/google" style={{...button,textDecoration:"none",marginTop:12,background:"#20252d",color:"#f5f7fa",border:"1px solid #303640"}}>Continue with Google</a><button onClick={()=>{setMode(mode==="signup"?"login":"signup");setError("")}} style={{marginTop:22,width:"100%",background:"none",border:0,color:"#d7dce3",cursor:"pointer"}}>{mode==="signup"?"Already have an account? Sign in":"New to TenTran AI? Create an account"}</button></div></main>}
const input={width:"100%",boxSizing:"border-box" as const,border:"1px solid #303640",background:"#0c0f13",color:"#fff",borderRadius:10,padding:"12px 13px",outline:"none"};
const button={display:"flex",justifyContent:"center",alignItems:"center",gap:8,border:0,borderRadius:10,padding:"12px 16px",background:"#f5f7fa",color:"#0b0d10",fontWeight:700,cursor:"pointer"};
