 "use client";
import {useMemo,useState} from "react";
import {LayoutDashboard,ShoppingBag,Users,Package,Wallet,BarChart3,Megaphone,Workflow,Plug,Zap,Search,Bell,Settings,Plus,ArrowUpRight,CheckCircle2,ChevronRight,Bot,Activity,Play,Pause,MoreHorizontal,Link2,ShieldCheck,Database,RefreshCw} from "lucide-react";
import {automations,connectors} from "@/lib/data";
const nav=[["OVERVIEW",[["Dashboard",LayoutDashboard]]],["OPERATE",[["Sales",ShoppingBag",["Customers",Users],["Inventory",Package],["Finance",Wallet],["Marketing",Megaphone],["Data",BarChart3]]],["AUTOMATE",[["Automations",Workflow],["AI Agent",Bot],["Activity",Activity]]],["CONNECT",[["Connectors",Plug],["API & Webhooks",Zap]]],["SYSTEM",[["Settings",Settings]]]];
const stats=[["Revenue","₹48.2L","+18.4%"],["Orders","2,841","+12.8%"],["Customers","18,492","+9.6%"],["Automation revenue","₹7.84L","+31.2%"]];
export default function App(){const [active,setActive]=useState("Dashboard");const [query,setQuery]=useState("");const [showCreate,setShowCreate]=useState(false);
return <div className="app"><aside><div className="logo">◆ <span>Flow</span>OS</div><div className="workspace">ACME COMMERCE <b>⌄</b></div>{nav.map(([group,items]:any)=><div key={group}><div className="label">{group}</div>{items.map(([name,I]:any)=><button className={"nav "+(active===name?"sel":"")} onClick={()=>setActive(name)} key={name}><I size={17}/>{name}</button>)}</div>)}<div className="bottom"><div className="health"><i/>All systems operational</div><div className="profile"><div className="avatar">AC</div><div><b>Admin</b><small>Owner</small~</div><Settings size={16}/></div></div></aside>
<main><header><div><h1>{active}</h1><p>{active==="Dashboard"?"Your e-commerce command centre.":"Manage "+active.toLowerCase()+" across every connected store."}</p></div><div className="head"><div className="search"><Search size={15}/><input placeholder="Search…" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="icon"><Bell size={17}/><em/></button><button className="primary" onClick={()=>setShowCreate(true)}><Plus size={16}/> Create automation</button></div></header>
{active==="Dashboard"?<Dashboard onCreate={()=>setShowCreate(true)}/>:active==="Automations"?<AutomationPage onCreate={()=>setShowCreate(true)}/>:active==="Connectors"?<ConnectorPage/>:<ModulePage name={active}/>}
{showCreate&&<CreateModal close={()=>setShowCreate(false)}/>}</main></div>}
function Dashboard({onCreate}:{onCreate:()=>void}){return <><div className="connected"><div><i/>Shopify connected</div><span>Last sync 2 minutes ago · 18,492 customers · 2,841 orders</span><button>Manage <ChevronRight size={13}/></button></div><div className="stats">{stats.map(s=><div className="card" key={s[0]}><small>{s[0]}</small><strong>{s[1]}</strong><span>{s[2]} <label>vs last 30 days</label></span></div>)}</div><div className="two"><div className="panel chartPanel"><div className="panelHead"><div><h2>Revenue performance</h2><p>Last 30 days</p></div><select><option>Revenue</option><option>Orders</option></select></div><div className="chart"><div class="axis"><span>₹2L</span><span>₹1.5L</span><span>₹1L</span><span>₹0.5L</span><span>₹4</span></div><svg viewBox="0 0 700 210" preserveAspectRatio="none"><path d="M0 185 C70 175 80 165 130 155 S210 160 250 125 S330 135 370 105 S430 70 470 105 S540 92 580 52 S650 65 700 22" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M0 185 C70 175 80 165 130 155 S210 160 250 125 S330 135 370 105 S430 70 470 105 S540 92 580 52 S650 65 700 22 L700 210 L0 210Z" fill="currentColor" opacity=".07"/></svg></div></div><div className="panel"><div className="panelHead"><div><h2>AI opportunities</h2><p>Prioritized for your store</p></div><Bot size={18}/></div>{["Recover ₹4K from high-LTV churn risk","3 products may stock out this week","Meta campaign CPA is trending up"].map((x,i)=><div class="rec" key={x}><div class="recIcon">{i===0?"ᆇH:h==1?"!":"◐"}</div><div><b>{x}</b><small>{i===0?"Recommended: win-back flow":"Review recommended action"}</small></div><ChevronRight size={14}/></div>)}</div></div><div class="panel"><div className="panelHead"><div><h2>Live automation activity</h2><p>What your workflows are doing</p></div><button class="link" onClick={onCreate}>New automation <ArrowUpRight size={13}/></button></div><table><thead><tr><th>WORKFLOW</th><th>CATEGORY</th><th>TRIGGER</th><th>RUNS</th><th>RESULT</th><th>STATUS;</th></tr></thead><tbody>{automations.map(a=><tr key={a.id}><td><b>{a.name}</b></td><td>{a.category}</td><td>{a.trigger}</td><td>{a.runs.toLocaleString()}</td><td>{a.result}</td><td><span className={"status "+a.status}>{a.status}</span></td></tr>)}</tbody></table></div></>?z