import {createCipheriv,createDecipheriv,createHash,randomBytes} from "crypto";
import * as fs from "fs"; import * as path from "path"; import {getCurrentUser} from "@/lib/authStore";
export type CanonicalRecord={id:string;workspaceId:string;provider:string;sourceId:string;type:"order"|"customer"|"product"|"inventory"|"payment"|"shipment"|"event";data:Record<string,unknown>;syncedAt:number};
export type Execution={id:string;workspaceId:string;workflowId:string;status:"queued"|"running"|"waiting_approval"|"succeeded"|"failed"|"dead_letter";trigger:string;action:string;attempts:number;maxAttempts:number;idempotencyKey:string;error?:string;createdAt:number;updatedAt:number;approvalId?:string};
export type Approval={id:string;workspaceId:string;executionId:string;status:"pending"|"approved"|"rejected";reason:string;createdAt:number;resolvedAt?:number};
export type Audit={id:string;workspaceId:string;type:string;actor:string;entityId:string;details:Record<string,unknown>;createdAt:number};
type State={records:CanonicalRecord[];executions:Execution[];approvals:Approval[];audits:Audit[];keys:string[]};
const key=()=>createHash("sha256").update(process.env.ENCRYPTION_KEY||"tentran-local-runtime").digest();
const file=()=>path.join(process.env.NODE_ENV==="production"?"/tmp":process.cwd(),".flowos","runtime.json");
function enc(s:string){const iv=randomBytes(12),c=createCipheriv("aes-256-gcm",key(),iv),d=Buffer.concat([c.update(s),c.final()]);return JSON.stringify({iv:iv.toString("base64"),tag:c.getAuthTag().toString("base64"),d:d.toString("base64")});}
function dec(s:string){const o=JSON.parse(s),d=createDecipheriv("aes-256-gcm",key(),Buffer.from(o.iv,"base64"));d.setAuthTag(Buffer.from(o.tag,"base64"));return Buffer.concat([d.update(Buffer.from(o.d,"base64")),d.final()]).toString();}
function load():State{try{return JSON.parse(dec(fs.readFileSync(file(),"utf8")));}catch{return {records:[],executions:[],approvals:[],audits:[],keys:[]};}}
function save(s:State){fs.mkdirSync(path.dirname(file()),{recursive:true});fs.writeFileSync(file(),enc(JSON.stringify(s)),{mode:0o600});}
export async function workspace(){const u=await getCurrentUser();if(!u)throw new Error("unauthorized");return `user:${u.id}`;}
export async function addRecords(w:string,records:CanonicalRecord[]){const s=load();s.records=s.records.filter(r=>r.workspaceId!==w||!records.some(n=>n.provider===r.provider&&n.sourceId===r.sourceId));s.records.push(...records);save(s);return records.length;}
export async function listRecords(w:string){return load().records.filter(r=>r.workspaceId===w);}
export async function queueExecution(w:string,input:Pick<Execution,"workflowId"|"trigger"|"action">){const s=load(),now=Date.now(),idempotencyKey=`${input.workflowId}:${input.trigger}:${input.action}`;const prior=s.executions.find(e=>e.workspaceId===w&&e.idempotencyKey===idempotencyKey&&e.status!=="failed");if(prior)return prior;const e:Execution={id:randomBytes(12).toString("hex"),workspaceId:w,...input,status:"queued",attempts:0,maxAttempts:3,idempotencyKey,createdAt:now,updatedAt:now};s.executions.push(e);s.audits.push({id:randomBytes(8).toString("hex"),workspaceId:w,type:"execution.queued",actor:"system",entityId:e.id,details:{trigger:input.trigger},createdAt:now});save(s);return e;}
export async function listExecutions(w:string){return load().executions.filter(e=>e.workspaceId===w).sort((a,b)=>b.updatedAt-a.updatedAt);}
export async function approveExecution(w:string,id:string,approved:boolean){const s=load(),e=s.executions.find(x=>x.workspaceId===w&&x.id===id);if(!e)throw new Error("execution_not_found");const a=s.approvals.find(x=>x.executionId===id&&x.workspaceId===w);if(!a)throw new Error("approval_not_found");a.status=approved?"approved":"rejected";a.resolvedAt=Date.now();e.status=approved?"queued":"failed";e.updatedAt=Date.now();e.error=approved?undefined:"Rejected by owner";s.audits.push({id:randomBytes(8).toString("hex"),workspaceId:w,type:approved?"approval.approved":"approval.rejected",actor:"owner",entityId:id,details:{},createdAt:Date.now()});save(s);return e;}
export async function requireApproval(w:string,e:Execution,reason:string){const s=load(),a:Approval={id:randomBytes(12).toString("hex"),workspaceId:w,executionId:e.id,status:"pending",reason,createdAt:Date.now()};e.status="waiting_approval";e.approvalId=a.id;e.updatedAt=Date.now();s.approvals.push(a);save(s);return a;}
export async function listApprovals(w:string){return load().approvals.filter(a=>a.workspaceId===w).sort((a,b)=>b.createdAt-a.createdAt);}
export async function audit(w:string,type:string,entityId:string,details:Record<string,unknown>){const s=load();s.audits.push({id:randomBytes(8).toString("hex"),workspaceId:w,type,actor:"system",entityId,details,createdAt:Date.now()});save(s);}
export async function listAudits(w:string){return load().audits.filter(a=>a.workspaceId===w).sort((a,b)=>b.createdAt-a.createdAt);}
